checkpoint_dir: ./logs/tokenizer_ckpts

patch_size: 8

latent_dim: 384
compile: True 
num_heads: 8
num_layers: 12
num_latents: 32
bottleneck_dim: 32
dropout: 0.05
mlp_ratio: 2.67
time_embedding_every: 4
mae_prob_min: 0.0
mae_prob_max: 0.9
latents_only_time: true

gradient_checkpointing: false  # Enable to save memory

optim:
  lr: 0.0003  
  weight_decay: 0.01
  max_steps: 2000
  grad_accum: 2  
  warmup_steps: 2000
  min_lr: 1.0e-6

lpips:
  weight: 0.2
  frac: 0.5
  net: "alex"

dataloader:
  batch_size: 8  
  num_workers: 8
  pin_memory: true
  drop_last: true
  persistent_workers: true
  prefetch_factor: 20

wandb:
  mode: "online"
  project: "Dreamer"
  entity: null

training:
  maxsteps: 1000000
  log_every: 100
  print_every: 100
  viz_every: 500
  viz_max_items: 4
  viz_max_T: 8
  ckpt_dir: "./logs/tokenizer_ckpts"
  save_every: 5000
  # Validation settings
  val_every: 1000
  val_max_batches: 50
  val_lpips_frac: 0.25
