checkpoint_dir: ./logs/tokenizer_ckpts

patch_size: 8

latent_dim: 512
compile: True 
num_layers: 12
num_latents: 32
bottleneck_dim: 32
dropout: 0.05
mlp_ratio: 6.00
mae_prob_min: 0.0
mae_prob_max: 0.9
time_embedding_every: 4
latents_only_time: true
gradient_checkpointing: true  # Enable to save memory


# Attention configuration
attention:
  heads: 24
  kv_heads: 8  # Number of KV heads for GQA (must divide num_heads)
  head_dim : 16
  dropout: 0.05
  qk_norm: true  # Use QK normalization
  rope_base: 10000.0  # RoPE base frequency
  rope_max_t: 16  # Max temporal positions
  rope_max_s: 512  # Max spatial positions
  bias: false

optim:
  lr: 0.0003  
  weight_decay: 0.01

opt_sched:
  min_lr: 1.0e-6
  warmup_steps: 2000

lpips:
  weight: 0.2
  frac: 0.5
  net: "alex"

dataloader:
  batch_size: 32
  num_workers: 8
  pin_memory: true
  drop_last: true
  persistent_workers: true
  prefetch_factor: 4

wandb:
  mode: "online"
  project: "Dreamer"
  entity: null

training:
  grad_accum: 2
  maxsteps: 2000000
  log_every: 10
  print_every: 100
  viz_every: 500
  viz_max_items: 4
  viz_max_T: 8
  ckpt_dir: "./logs/tokenizer_ckpts"
  save_every: 5000
  # Validation settings
  val_every: 1000
  val_lpips_frac: 0.25
